---
APPLY_FIXES: none
VALIDATE_ALL_CODEBASE: true

ENABLE_LINTERS:
  - PYTHON_RUFF
  - YAML_YAMLLINT
  - JSON_JSONLINT
  - MARKDOWN_MARKDOWNLINT
  - ACTION_ACTIONLINT

FILTER_REGEX_EXCLUDE: (\.git/|__pycache__/|\.venv/)
